
import dss_abdominal.Patient


rule "Hernia"
    dialect "java"
    when
        d1 : Patient(bulks==true)
    then
        d1.setDiseaseName("Hernia");
        System.out.println("The first approximation of the diagnosis is:"+d1.getDiseaseName());
end

rule "Colitis"
    dialect "java"
    when
        d2 : Patient(poo==true)
    then
        d2.setDiseaseName("Ulcerative Colitis");
        System.out.println("The first approximation of the diagnosis is:"+d2.getDiseaseName());
end

rule "Colitis2"
    dialect "java"
    when
        d3 : Patient(nausea==false)
    then
        d3.setDiseaseName("Ulcerative Colitis");
        System.out.println("The first approximation of the diagnosis is:"+d3.getDiseaseName());
end

rule "Celiac"
    dialect "java"
    when
        d4 : Patient(dermatitis==true)
    then
        d4.setDiseaseName("Celiac Disease");
        System.out.println("The first approximation of the diagnosis is:"+d4.getDiseaseName());
end

rule "Diverticulosis"
    dialect "java"
    when
        d5 : Patient(chills==true)
    then
        d5.setDiseaseName("Diverticulosis");
        System.out.println("The first approximation of the diagnosis is:"+d5.getDiseaseName());
end


rule "Crohns"
    dialect "java"
    when
        d6 : Patient(melenas==true)
    then
        d6.setDiseaseName("Crohns Disease");
        System.out.println("The first approximation of the diagnosis is:"+d6.getDiseaseName());
end

rule "Enterocolitis"
    dialect "java"
    when
        d7 : Patient(ulcers==true)
    then
        d7.setDiseaseName("Infectious Enterocolitis");
        System.out.println("The first approximation of the diagnosis is:"+d7.getDiseaseName());
end

rule "Hernia2"
    dialect "java"
    when
        d8 : Patient(diarrhea==false)
    then
        d8.setDiseaseName("Inguinal or Abdominal Hernia");
        System.out.println("The first approximation of the diagnosis is:"+d8.getDiseaseName());
end

rule "Appendicitis"
    dialect "java"
    when
        d9 : Patient(fever==true)
    then
        d9.setDiseaseName("Appendicitis");
        System.out.println("The first approximation of the diagnosis is:"+d9.getDiseaseName());
end
 
rule "Colorectal"
    dialect "java"
    when
        d10 : Patient(genetic==true)
    then
        d10.setDiseaseName("Colorectal Cancer");
        System.out.println("The first approximation of the diagnosis is:"+d10.getDiseaseName());
        
end
