
import abdominalproject.Disease


rule "Hernia"
    dialect "java"
    when:
        d1: Disease(bulk==true)
    then:
        d1.setDiseaseName(“Hernia”)
        System.out.println("The first approximation of the diagnosis is:"+d1.getDiseaseName())
end

rule "Colitis"
    dialect "java"
    when:
        d2: Disease(poo==true)
    then:
        d2.setDiseaseName(“Ulcerative Colitis”)
        System.out.println("The first approximation of the diagnosis is:"+d2.getDiseaseName())
end

rule "Colitis2"
    dialect "java"
    when:
        d3: Disease(nausea==true)
    then:
        d3.setDiseaseName(“Ulcerative Colitis”)
        System.out.println("The first approximation of the diagnosis is:"+d3.getDiseaseName())
end

rule "Celiac"
    dialect "java"
    when:
        d4: Disease(dermatitis==true)
    then:
        d4.setDiseaseName(“Celiac Disease”)
        System.out.println("The first approximation of the diagnosis is:"+d4.getDiseaseName()
end

rule "Diverticulosis"
    dialect "java"
    when:
        d5: Disease(chills==true)
    then:
        d5.setDiseaseName(“Diverticulosis”)
        System.out.println("The first approximation of the diagnosis is:"+d5.getDiseaseName()
end


rule "Crohns"
    dialect "java"
    when:
        d6: Disease(melenas==true)
    then:
        d6.setDiseaseName(“Crohns Disease”)
        System.out.println("The first approximation of the diagnosis is:"+d6.getDiseaseName()
end

rule "Enterocolitis"
    dialect "java"
    when:
        d7: Disease(ulcers==true)
    then:
        d7.setDiseaseName(“Infectious Enterocolitis”)
        System.out.println("The first approximation of the diagnosis is:"+d7.getDiseaseName()
end

rule "Hernia"
    dialect "java"
    when:
        d8: Disease(diarrhea==true)
    then:
        d8.setDiseaseName(“Inguinal or Abdominal Hernia”)
        System.out.println("The first approximation of the diagnosis is:"+d8.getDiseaseName()
end



 
